/**
 * Minimal example: write a file to a feature branch on a repo you
 * have write access to, then open a PR against the default branch.
 *
 * Run:
 *
 *   GITHUB_TOKEN=ghp_... \
 *   TARGET_REPO=https://github.com/yourname/playground \
 *     npx tsx examples/github-write-and-pr.ts
 *
 * Required token scope: `contents: write` and `pull-requests: write`
 * on the target repo.
 *
 * The branch name + commit message are timestamped so re-runs don't
 * conflict.
 */

import { envFromProcessEnv } from '@verevoir/sources';
import { writeFile, openPullRequest, getDefaultBranch } from '@verevoir/sources/github';

async function main(): Promise<void> {
  const env = envFromProcessEnv();
  if (!env) {
    console.error('GITHUB_TOKEN not set.');
    process.exit(1);
  }
  const repoUrl = process.env.TARGET_REPO;
  if (!repoUrl) {
    console.error('TARGET_REPO not set (e.g. https://github.com/you/repo).');
    process.exit(1);
  }

  const ts = new Date().toISOString().replace(/[:.]/g, '-');
  const branch = `verevoir-sources-example/${ts}`;
  const path = `examples/${ts}.md`;
  const content = `# Hello from @verevoir/sources\n\nWritten at ${ts}.\n`;

  await writeFile(env, repoUrl, path, content, branch, `examples: add ${path}`);
  console.log(`Wrote ${path} on branch ${branch}.`);

  const base = await getDefaultBranch(env, repoUrl);
  const prUrl = await openPullRequest(
    env,
    repoUrl,
    branch,
    base,
    `examples: add ${path}`,
    `Generated by @verevoir/sources example.`
  );
  console.log(`Opened PR: ${prUrl}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
